enum RequestState {
  initialState,
  webSiteLoading,
  categoryLoading,
  subCategoryLoading,
  searchLoading,
  postLoading,
  paginateLoading,
  //-------------------
  insertLoading,
  updateLoading,
  deleteLoading,
  toggleSeenLoading,
  updateFilterNameLoading,
  //-------------------
  webSiteLoaded,
  categoryLoaded,
  subCategoryLoaded,
  searchLoaded,
  postLoaded,
  paginateLoaded,
  //-------------------
  insertDone,
  updateDone,
  updateFilterNameDone,
  deleteDone,
  toggleSeenDone,
  //-------------------
  webSiteError,
  categoryError,
  subCategoryError,
  searchError,
  postError,
  paginateError,
  //-------------------
  insertError,
  updateError,
  updateFilterNameError,
  deleteError,
  toggleSeenError
}